<a href="https://colab.research.google.com/github/Kusumitha-Muddam/My-first-project-on-Hashing/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving house.csv to house.csv

In [ ]:
import pandas as pd
df=pd.read_csv("house.csv")
print(df.head())

            date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  5/2/2014 0:00   313000.0         3       1.50         1340      7912
1  5/2/2014 0:00  2384000.0         5       2.50         3650      9050
2  5/2/2014 0:00   342000.0         3       2.00         1930     11947
3  5/2/2014 0:00   420000.0         3       2.25         2000      8030
4  5/2/2014 0:00   550000.0         4       2.50         1940     10500

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955
1     2.0           0     4          5        3370            280      1921
2     1.0           0     0          4        1930              0      1966
3     1.0           0     0          4        1000           1000      1963
4     1.0           0     0          4        1140            800      1976

   yr_renovated                    street       city  statezip country
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA
1             0           709 W Blaine St    Seattle  WA 98119     USA
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA
3             0           857 170th Pl NE   Bellevue  WA 98008     USA
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

1.IMPORT

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.impute import SimpleImputer

2.**LOAD** **DATASET**

In [ ]:
df=pd.read_csv("house.csv")
print(df.head())
print(df.shape)

            date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  5/2/2014 0:00   313000.0         3       1.50         1340      7912
1  5/2/2014 0:00  2384000.0         5       2.50         3650      9050
2  5/2/2014 0:00   342000.0         3       2.00         1930     11947
3  5/2/2014 0:00   420000.0         3       2.25         2000      8030
4  5/2/2014 0:00   550000.0         4       2.50         1940     10500

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955
1     2.0           0     4          5        3370            280      1921
2     1.0           0     0          4        1930              0      1966
3     1.0           0     0          4        1000           1000      1963
4     1.0           0     0          4        1140            800      1976

   yr_renovated                    street       city  statezip country
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA
1             0           709 W Blaine St    Seattle  WA 98119     USA
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA
3             0           857 170th Pl NE   Bellevue  WA 98008     USA
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA
(4600, 18)

**3**.**QUICK** **INSPECTION**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   int64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(3), int64(10), object(5)
memory usage: 647.0+ KB

In [ ]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

4.**DEFINE TARGET AND FEATURES**

In [ ]:
#target
y=df['price']

#features
x=df.drop(columns=['price'])

In [ ]:
x.head(2)

,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,5/2/2014 0:00,3,1.5,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,5/2/2014 0:00,5,2.5,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA

In [ ]:
y.head(2)

0     313000.0
1    2384000.0
Name: price, dtype: float64

In [ ]:
x.drop(columns=['statezip','street','country'],inplace=True)

In [ ]:
x.columns

Index(['date', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
       'yr_built', 'yr_renovated', 'city'],
      dtype='object')

**5.FEATURE ENGINEERING(DATE->YEAR/MONTH/DAY OF WEEK)**

In [ ]:
#Convert Date to Datetime and extracyt uuseful componenets
x['date']=pd.to_datetime(x['date'],errors="coerce",dayfirst=True)
x['soldyear']=x['date'].dt.year
x['soldmonth']=x['date'].dt.month
x['soldday']=x['date'].dt.day

# Drop row date afetr extracting features
x.drop(columns=['date'],inplace=True)

,date,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,city,soldyear,soldmonth,soldday
0,2014-02-05,3,1.5,1340,7912,1.5,0,0,3,1340,0,1955,2005,Shoreline,2014.0,2.0,5.0
1,2014-02-05,5,2.5,3650,9050,2.0,0,4,5,3370,280,1921,0,Seattle,2014.0,2.0,5.0

**6.SELECT NUMERIC VS CATEGORICAL COLUMNS**

In [ ]:
num_x=x.select_dtypes(include="number")
cat_x=x.select_dtypes(exclude="number")
print(cat_x)

           date       city
0    2014-02-05  Shoreline
1    2014-02-05    Seattle
2    2014-02-05       Kent
3    2014-02-05   Bellevue
4    2014-02-05    Redmond
...         ...        ...
4595 2014-09-07    Seattle
4596 2014-09-07   Bellevue
4597 2014-09-07     Renton
4598 2014-10-07    Seattle
4599 2014-10-07  Covington

[4600 rows x 2 columns]

**7 PREPROCESSING PIPELINE(IMPUTE+ENCODE+SCALE)**

In [ ]:
# Numeric:median impute+scale
num_transformation=Pipeline(steps=[("imputer",SimpleImputer(strategy="median")),("scaling",StandardScaler())])
# Categorical:most_frequent(mode) impute+one-hot encode
cat_transformation=Pipeline(steps=[("imputer",SimpleImputer(strategy="most_frequent")),("encoding",OneHotEncoder(handle_unknown="ignore"))])
preprocessor=ColumnTransformer(transformers=[("num",num_transformation,num_x),("cat",cat_transformation,cat_x)],remainder="drop")
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                       bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0            3       1.50         1340      7912     1.5           0     0
1            5       2.50         3650      9050     2.0           0     4
2            3       2.00         1930     11947     1.0           0     0
3            3       2.25         2000      8030     1.0           0     0
4            4       2.50         1940     10500     1.0           0     0
...        ...        ...          ...       ...     ...         ...   ...
4595         3       1.75         1510      6360     1.0           0     0
4596         3       2.50         1460      7573     2....
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                            date       city
0    2014-02-05  Shoreline
1    2014-02-05    Seattle
2    2014-02-05       Kent
3    2014-02-05   Bellevue
4    2014-02-05    Redmond
...         ...        ...
4595 2014-09-07    Seattle
4596 2014-09-07   Bellevue
4597 2014-09-07     Renton
4598 2014-10-07    Seattle
4599 2014-10-07  Covington

[4600 rows x 2 columns])])

**8.TRAIN-TEST SPLIT**

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_test.shape

(920, 17)

**ENCODING**

In [8]:
#sample dataset
import pandas as pd
data={
    "city":["hyd","chennai","Banglore","hyd","chennai"],
    "edu":["degree","Masters","PhD","degree","Masters"],
}
df=pd.DataFrame(data)
df

       city      edu
0       hyd   degree
1   chennai  Masters
2  Banglore      PhD
3       hyd   degree
4   chennai  Masters

In [10]:
# LABEL ENCODING

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['edu encoded']=le.fit_transform(df['edu'])
df

       city      edu  edu encoded
0       hyd   degree            2
1   chennai  Masters            0
2  Banglore      PhD            1
3       hyd   degree            2
4   chennai  Masters            0

In [11]:
# ONE-HOT ENCODING

pd.get_dummies(df['city'])

   Banglore  chennai    hyd
0     False    False   True
1     False     True  False
2      True    False  False
3     False    False   True
4     False     True  False

SCALING:

1.  StandardScaler
2. MinMaxScaler

In [14]:
import pandas as pd
df={
    "age":[20,25,30,35,40],
    "income":[10000,20000,30000,40000,50000]
}
df=pd.DataFrame(df)
df

   age  income
0   20   10000
1   25   20000
2   30   30000
3   35   40000
4   40   50000

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df['age scaled']=scaler.fit_transform(df[['age']])
df['income scaled']=scaler.fit_transform(df[['income']])
df

   age  income  age scaled  income scaled
0   20   10000   -1.414214      -1.414214
1   25   20000   -0.707107      -0.707107
2   30   30000    0.000000       0.000000
3   35   40000    0.707107       0.707107
4   40   50000    1.414214       1.414214

In [17]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
df['ages']=ms.fit_transform(df[['age']])
df['incomes']=ms.fit_transform(df[['income']])
df

   age  income  age scaled  income scaled  ages  incomes
0   20   10000   -1.414214      -1.414214  0.00     0.00
1   25   20000   -0.707107      -0.707107  0.25     0.25
2   30   30000    0.000000       0.000000  0.50     0.50
3   35   40000    0.707107       0.707107  0.75     0.75
4   40   50000    1.414214       1.414214  1.00     1.00

In [ ]:










 21+0000000000000000-*0